// Java 14.0.1
// frostrivera19
// Project Euler Problem 29 : Distinct powers
// How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100
// and 2 ≤ b ≤ 100?
// https://projecteuler.net/archives
// Solved 07 Jun 2020

import java.util.HashSet;

public class Main {
    public static void main(String[] args) {
        int ans = distinctAb(2, 100);
        System.out.println(ans);
    }

    private static int distinctAb(int start, int last) {
        HashSet<Double> products = new HashSet<>();
        for (int a = start; a <= last; a++) {
            for (int b = start; b <= last; b++) {
                double result = Math.pow(a, b);
                products.add(result);
            }
        }
        return products.size();
    }

}